DESTINATION_CARDS = [
 {'cities': ['Boston', 'Miami'], 'points': 12},
 {'cities': ['Calgary', 'Phoenix'], 'points': 13},
 {'cities': ['Calgary', 'Salt Lake City'], 'points': 7},
 {'cities': ['Chicago', 'New Orleans'], 'points': 7},
 {'cities': ['Chicago', 'Santa Fe'], 'points': 9},
 {'cities': ['Dallas', 'New York'], 'points': 11},
 {'cities': ['Denver', 'El Paso'], 'points': 4},
 {'cities': ['Denver', 'Pittsburgh'], 'points': 11},
 {'cities': ['Duluth', 'El Paso'], 'points': 10},
 {'cities': ['Duluth', 'Houston'], 'points': 8},
 {'cities': ['Helena', 'Los Angeles'], 'points': 8},
 {'cities': ['Kansas City', 'Houston'], 'points': 5},
 {'cities': ['Los Angeles', 'Chicago'], 'points': 16},
 {'cities': ['Los Angeles', 'Miami'], 'points': 20},
 {'cities': ['Los Angeles', 'New York'], 'points': 21},
 {'cities': ['Montreal', 'Atlanta'], 'points': 9},
 {'cities': ['Montreal', 'New Orleans'], 'points': 13},
 {'cities': ['New York', 'Atlanta'], 'points': 6},
 {'cities': ['Portland', 'Nashville'], 'points': 17},
 {'cities': ['Portland', 'Phoenix'], 'points': 11},
 {'cities': ['San Francisco', 'Atlanta'], 'points': 17},
 {'cities': ['Saul St. Marie', 'Nashville'], 'points': 8},
 {'cities': ['Seattle', 'Los Angeles'], 'points': 9},
 {'cities': ['Seattle', 'New York'], 'points': 22},
 {'cities': ['Saul St. Marie', 'Oklahoma City'], 'points': 9},
 {'cities': ['Toronto', 'Miami'], 'points': 10},
 {'cities': ['Vancouver', 'Montreal'], 'points': 20},
 {'cities': ['Vancouver', 'Santa Fe'], 'points': 13},
 {'cities': ['Winnipeg', 'Houston'], 'points': 12},
 {'cities': ['Winnipeg', 'Little Rock'], 'points': 11},
]

ROUTES = [
  {'cities': ['Seattle', 'Vancouver'], 'length': 1, 'color': 'gray'},
  {'cities': ['Seattle', 'Vancouver'], 'length': 1, 'color': 'gray'},
  {'cities': ['Calgary', 'Vancouver'], 'length': 3, 'color': 'gray'},
  {'cities': ['Portland', 'Seattle'], 'length': 1, 'color': 'gray'},
  {'cities': ['Portland', 'Seattle'], 'length': 1, 'color': 'gray'},
  {'cities': ['Calgary', 'Seattle'], 'length': 4, 'color': 'gray'},
  {'cities': ['Helena', 'Seattle'], 'length': 6, 'color': 'yellow'},
  {'cities': ['Portland', 'Salt Lake City'], 'length': 6, 'color': 'blue'},
  {'cities': ['Portland', 'San Francisco'], 'length': 5, 'color': 'pink'},
  {'cities': ['Portland', 'San Francisco'], 'length': 5, 'color': 'green'},
  {'cities': ['Salt Lake City', 'San Francisco'], 'length': 5, 'color': 'white'},
  {'cities': ['Salt Lake City', 'San Francisco'], 'length': 5, 'color': 'orange'},
  {'cities': ['Los Angeles', 'San Francisco'], 'length': 3, 'color': 'pink'},
  {'cities': ['Los Angeles', 'San Francisco'], 'length': 3, 'color': 'yellow'},
  {'cities': ['El Paso', 'Los Angeles'], 'length': 6, 'color': 'black'},
  {'cities': ['El Paso', 'Houston'], 'length': 6, 'color': 'green'},
  {'cities': ['Las Vegas', 'Los Angeles'], 'length': 2, 'color': 'gray'},
  {'cities': ['Los Angeles', 'Phoenix'], 'length': 3, 'color': 'gray'},
  {'cities': ['Las Vegas', 'Salt Lake City'], 'length': 3, 'color': 'orange'},
  {'cities': ['Calgary', 'Helena'], 'length': 4, 'color': 'gray'},
  {'cities': ['Calgary', 'Winnipeg'], 'length': 6, 'color': 'white'},
  {'cities': ['Helena', 'Winnipeg'], 'length': 4, 'color': 'blue'},
  {'cities': ['Duluth', 'Helena'], 'length': 6, 'color': 'orange'},
  {'cities': ['Helena', 'Salt Lake City'], 'length': 3, 'color': 'pink'},
  {'cities': ['Denver', 'Helena'], 'length': 4, 'color': 'green'},
  {'cities': ['Helena', 'Omaha'], 'length': 5, 'color': 'red'},
  {'cities': ['Denver', 'Salt Lake City'], 'length': 3, 'color': 'red'},
  {'cities': ['Denver', 'Salt Lake City'], 'length': 3, 'color': 'yellow'},
  {'cities': ['Denver', 'Phoenix'], 'length': 5, 'color': 'white'},
  {'cities': ['Phoenix', 'Santa Fe'], 'length': 3, 'color': 'gray'},
  {'cities': ['El Paso', 'Phoenix'], 'length': 3, 'color': 'gray'},
  {'cities': ['Denver', 'Santa Fe'], 'length': 2, 'color': 'gray'},
  {'cities': ['El Paso', 'Santa Fe'], 'length': 2, 'color': 'gray'},
  {'cities': ['Dallas', 'El Paso'], 'length': 4, 'color': 'red'},
  {'cities': ['El Paso', 'Oklahoma City'], 'length': 5, 'color': 'yellow'},
  {'cities': ['Oklahoma City', 'Santa Fe'], 'length': 3, 'color': 'blue'},
  {'cities': ['Denver', 'Oklahoma City'], 'length': 4, 'color': 'red'},
  {'cities': ['Denver', 'Kansas City'], 'length': 4, 'color': 'orange'},
  {'cities': ['Denver', 'Kansas City'], 'length': 4, 'color': 'blue'},
  {'cities': ['Denver', 'Omaha'], 'length': 4, 'color': 'pink'},
  {'cities': ['Duluth', 'Winnipeg'], 'length': 4, 'color': 'black'},
  {'cities': ['Saul St. Marie', 'Winnipeg'], 'length': 6, 'color': 'grey'},
  {'cities': ['Duluth', 'Omaha'], 'length': 2, 'color': 'gray'},
  {'cities': ['Duluth', 'Omaha'], 'length': 2, 'color': 'gray'},
  {'cities': ['Duluth', 'Saul St. Marie'], 'length': 3, 'color': 'gray'},
  {'cities': ['Duluth', 'Toronto'], 'length': 6, 'color': 'pink'},
  {'cities': ['Chicago', 'Duluth'], 'length': 3, 'color': 'red'},
  {'cities': ['Chicago', 'Omaha'], 'length': 4, 'color': 'blue'},
  {'cities': ['Kansas City', 'Omaha'], 'length': 1, 'color': 'gray'},
  {'cities': ['Kansas City', 'Omaha'], 'length': 1, 'color': 'gray'},
  {'cities': ['Kansas City', 'Saint Louis'], 'length': 2, 'color': 'pink'},
  {'cities': ['Kansas City', 'Saint Louis'], 'length': 2, 'color': 'blue'},
  {'cities': ['Kansas City', 'Oklahoma City'], 'length': 2, 'color': 'gray'},
  {'cities': ['Kansas City', 'Oklahoma City'], 'length': 2, 'color': 'gray'},
  {'cities': ['Dallas', 'Oklahoma City'], 'length': 2, 'color': 'gray'},
  {'cities': ['Dallas', 'Oklahoma City'], 'length': 2, 'color': 'gray'},
  {'cities': ['Dallas', 'Houston'], 'length': 1, 'color': 'gray'},
  {'cities': ['Dallas', 'Houston'], 'length': 1, 'color': 'gray'},
  {'cities': ['Little Rock', 'Oklahoma City'], 'length': 2, 'color': 'gray'},
  {'cities': ['Dallas', 'Little Rock'], 'length': 2, 'color': 'gray'},
  {'cities': ['Houston', 'New Orleans'], 'length': 2, 'color': 'gray'},
  {'cities': ['Montreal', 'Saul St. Marie'], 'length': 5, 'color': 'black'},
  {'cities': ['Saul St. Marie', 'Toronto'], 'length': 2, 'color': 'gray'},
  {'cities': ['Chicago', 'Toronto'], 'length': 4, 'color': 'white'},
  {'cities': ['Chicago', 'Pittsburgh'], 'length': 3, 'color': 'orange'},
  {'cities': ['Chicago', 'Pittsburgh'], 'length': 3, 'color': 'black'},
  {'cities': ['Chicago', 'Saint Louis'], 'length': 2, 'color': 'white'},
  {'cities': ['Chicago', 'Saint Louis'], 'length': 2, 'color': 'green'},
  {'cities': ['Pittsburgh', 'Saint Louis'], 'length': 5, 'color': 'green'},
  {'cities': ['Nashville', 'Saint Louis'], 'length': 2, 'color': 'gray'},
  {'cities': ['Little Rock', 'Saint Louis'], 'length': 2, 'color': 'gray'},
  {'cities': ['Little Rock', 'New Orleans'], 'length': 3, 'color': 'green'},
  {'cities': ['Little Rock', 'Nashville'], 'length': 3, 'color': 'white'},
  {'cities': ['Miami', 'New Orleans'], 'length': 6, 'color': 'red'},
  {'cities': ['Atlanta', 'New Orleans'], 'length': 4, 'color': 'yellow'},
  {'cities': ['Atlanta', 'New Orleans'], 'length': 4, 'color': 'orange'},
  {'cities': ['Atlanta', 'Miami'], 'length': 5, 'color': 'blue'},
  {'cities': ['Charleston', 'Miami'], 'length': 4, 'color': 'pink'},
  {'cities': ['Atlanta', 'Charleston'], 'length': 2, 'color': 'gray'},
  {'cities': ['Charleston', 'Raleigh'], 'length': 2, 'color': 'gray'},
  {'cities': ['Atlanta', 'Nashville'], 'length': 1, 'color': 'gray'},
  {'cities': ['Atlanta', 'Raleigh'], 'length': 2, 'color': 'gray'},
  {'cities': ['Atlanta', 'Raleigh'], 'length': 2, 'color': 'gray'},
  {'cities': ['Nashville', 'Raleigh'], 'length': 3, 'color': 'black'},
  {'cities': ['Nashville', 'Pittsburgh'], 'length': 4, 'color': 'yellow'},
  {'cities': ['Raleigh', 'Washington'], 'length': 2, 'color': 'gray'},
  {'cities': ['Raleigh', 'Washington'], 'length': 2, 'color': 'gray'},
  {'cities': ['Pittsburgh', 'Raleigh'], 'length': 2, 'color': 'gray'},
  {'cities': ['Pittsburgh', 'Washington'], 'length': 2, 'color': 'gray'},
  {'cities': ['Pittsburgh', 'New York'], 'length': 2, 'color': 'white'},
  {'cities': ['Pittsburgh', 'New York'], 'length': 2, 'color': 'green'},
  {'cities': ['Pittsburgh', 'Toronto'], 'length': 2, 'color': 'gray'},
  {'cities': ['Montreal', 'Toronto'], 'length': 3, 'color': 'gray'},
  {'cities': ['Montreal', 'New York'], 'length': 3, 'color': 'blue'},
  {'cities': ['New York', 'Washington'], 'length': 2, 'color': 'black'},
  {'cities': ['New York', 'Washington'], 'length': 2, 'color': 'orange'},
  {'cities': ['Boston', 'New York'], 'length': 2, 'color': 'yellow'},
  {'cities': ['Boston', 'New York'], 'length': 2, 'color': 'red'},
  {'cities': ['Boston', 'Montreal'], 'length': 2, 'color': 'gray'},
  {'cities': ['Boston', 'Montreal'], 'length': 2, 'color': 'gray'},
]

ROUTE_VALUES = {
  1: 1,
  2: 2,
  3: 4,
  4: 7,
  5: 10,
  6: 15
}

CITIES = [
  'Atlanta',
  'Boston',
  'Calgary',
  'Charleston',
  'Chicago',
  'Dallas',
  'Denver',
  'Duluth',
  'El Paso',
  'Helena',
  'Houston',
  'Kansas City',
  'Las Vegas',
  'Los Angeles',
  'Little Rock',
  'Miami',
  'Montreal',
  'Nashville',
  'New Orleans',
  'New York',
  'Oklahoma City',
  'Omaha',
  'Phoenix',
  'Pittsburgh',
  'Portland',
  'Raleigh',
  'Saint Louis',
  'Salt Lake City',
  'San Francisco',
  'Santa Fe',
  'Saul St. Marie',
  'Seattle',
  'Toronto',
  'Vancouver',
  'Washington',
  'Winnipeg'
]


# API calls:
# get all routes from city; limit to available
# get all possible destinations from city A to city B
# get all available routes